#pragma once

#define MAX_CBUFFERS_AMOUNT D3D11_COMMONSHADER_CONSTANT_BUFFER_API_SLOT_COUNT
#define MAX_SAMPLERS_AMOUNT D3D11_COMMONSHADER_SAMPLER_SLOT_COUNT
#define MAX_SRVS_AMOUNT D3D11_COMMONSHADER_INPUT_RESOURCE_SLOT_COUNT
#define MAX_SOBUFFERS_AMOUNT D3D11_SO_BUFFER_SLOT_COUNT
#define UAVS_START_SLOT D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT
#define MAX_UAVS_AMOUNT (D3D11_1_UAV_SLOT_COUNT - UAVS_START_SLOT)

class DeviceReference {
protected:
	ID3D11Device*			m_pDevice;
	ID3D11DeviceContext*	m_pContext;
public:
	DeviceReference();
};
